// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameAlbum = "albums"

// Album mapped from table <albums>
type Album struct {
	AlbumID  uint   `gorm:"column:AlbumId;primaryKey;autoIncrement:false;not null" json:"AlbumId"`
	Title    string `gorm:"column:Title;size:160" json:"Title"`
	ArtistID int32  `gorm:"column:ArtistId;not null" json:"ArtistId"`
}

// TableName Album's table name
func (*Album) TableName() string {
	return TableNameAlbum
}
